package com.spareparts.dto;

import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

@Data
public class PurchaseOrderRequest {
    private Long branchId;
    private Long supplierId;
    private String status;
    private Boolean isAutoGenerated;
    private LocalDateTime expectedDate;
    private String notes;
    private List<PurchaseOrderItemRequest> items;

    @Data
    public static class PurchaseOrderItemRequest {
        private Long productId;
        private Integer quantity;
        private Double estimatedPrice;
        private Boolean suggestedByAi;
        private String reason;
    }
}
