package com.spareparts.service;

import com.spareparts.dto.PurchaseOrderRequest;
import com.spareparts.model.*;
import com.spareparts.config.TenantContext;
import com.spareparts.repository.PurchaseOrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class PurchaseOrderService {
    private final PurchaseOrderRepository purchaseOrderRepository;
    private final ProductService productService;
    private final SupplierService supplierService;
    private final BranchService branchService;

    public List<PurchaseOrder> getPurchaseOrders(Long branchId) {
        Long businessId = TenantContext.getBusinessId();
        if (branchId != null) {
            return purchaseOrderRepository.findByBusinessIdAndBranchIdOrderByCreatedAtDesc(businessId, branchId);
        }
        return purchaseOrderRepository.findByBusinessIdOrderByCreatedAtDesc(businessId);
    }

    public PurchaseOrder getPurchaseOrderById(Long id) {
        return purchaseOrderRepository.findById(id)
                .filter(po -> po.getBusiness().getId().equals(TenantContext.getBusinessId()))
                .orElseThrow(() -> new RuntimeException("Purchase Order not found"));
    }

    @Transactional
    public PurchaseOrder createPurchaseOrder(PurchaseOrderRequest request) {
        Long businessId = TenantContext.getBusinessId();
        Business business = new Business();
        business.setId(businessId);

        PurchaseOrder po = new PurchaseOrder();
        po.setBusiness(business);
        
        if (request.getBranchId() != null) {
            po.setBranch(branchService.getBranchById(request.getBranchId()));
        }
        
        po.setSupplier(supplierService.getSupplierById(request.getSupplierId()));
        po.setStatus(request.getStatus() != null ? request.getStatus() : "DRAFT");
        po.setNotes(request.getNotes());
        po.setExpectedDate(request.getExpectedDate());
        po.setIsAutoGenerated(request.getIsAutoGenerated() != null ? request.getIsAutoGenerated() : false);

        double estimatedTotal = 0.0;
        
        for (PurchaseOrderRequest.PurchaseOrderItemRequest itemReq : request.getItems()) {
            Product product = productService.getProductById(itemReq.getProductId());
            
            PurchaseOrderItem item = new PurchaseOrderItem();
            item.setPurchaseOrder(po);
            item.setProduct(product);
            item.setRequestedQuantity(itemReq.getQuantity());
            
            double estimatedPrice = itemReq.getEstimatedPrice() != null ? itemReq.getEstimatedPrice() : product.getPrice();
            item.setEstimatedPrice(estimatedPrice);
            item.setSuggestedByAi(itemReq.getSuggestedByAi() != null ? itemReq.getSuggestedByAi() : false);
            item.setReason(itemReq.getReason());
            
            estimatedTotal += (estimatedPrice * itemReq.getQuantity());
            po.getItems().add(item);
        }
        
        po.setEstimatedTotal(estimatedTotal);
        return purchaseOrderRepository.save(po);
    }

    @Transactional
    public PurchaseOrder createSystemPurchaseOrder(PurchaseOrderRequest request, Long businessId) {
        Business business = new Business();
        business.setId(businessId);

        PurchaseOrder po = new PurchaseOrder();
        po.setBusiness(business);
        
        if (request.getBranchId() != null) {
            po.setBranch(branchService.getBranchById(request.getBranchId()));
        }
        
        po.setSupplier(supplierService.getSupplierById(request.getSupplierId()));
        po.setStatus(request.getStatus() != null ? request.getStatus() : "DRAFT");
        po.setNotes(request.getNotes());
        po.setExpectedDate(request.getExpectedDate());
        po.setIsAutoGenerated(request.getIsAutoGenerated() != null ? request.getIsAutoGenerated() : false);

        double estimatedTotal = 0.0;
        
        for (PurchaseOrderRequest.PurchaseOrderItemRequest itemReq : request.getItems()) {
            Product product = productService.getProductById(itemReq.getProductId());
            
            PurchaseOrderItem item = new PurchaseOrderItem();
            item.setPurchaseOrder(po);
            item.setProduct(product);
            item.setRequestedQuantity(itemReq.getQuantity());
            
            double estimatedPrice = itemReq.getEstimatedPrice() != null ? itemReq.getEstimatedPrice() : product.getPrice();
            item.setEstimatedPrice(estimatedPrice);
            item.setSuggestedByAi(itemReq.getSuggestedByAi() != null ? itemReq.getSuggestedByAi() : false);
            item.setReason(itemReq.getReason());
            
            estimatedTotal += (estimatedPrice * itemReq.getQuantity());
            po.getItems().add(item);
        }
        
        po.setEstimatedTotal(estimatedTotal);
        return purchaseOrderRepository.save(po);
    }

    @Transactional
    public PurchaseOrder updatePurchaseOrderStatus(Long id, String status) {
        PurchaseOrder po = getPurchaseOrderById(id);
        po.setStatus(status);
        return purchaseOrderRepository.save(po);
    }
    
    @Transactional
    public void deletePurchaseOrder(Long id) {
        PurchaseOrder po = getPurchaseOrderById(id);
        purchaseOrderRepository.delete(po);
    }
}
