import React, { useEffect, useState } from 'react';
import { Box, Typography, Button, Card, CardContent, Grid, Chip, Table, TableBody, TableCell, TableHead, TableRow, IconButton } from '@mui/material';
import { Brain, FileText, Check, X, Eye } from 'lucide-react';
import { api } from '../api/client';

export default function PurchaseOrders() {
  const [orders, setOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const loadOrders = () => {
    setLoading(true);
    api.getPurchaseOrders()
      .then(setOrders)
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadOrders();
  }, []);

  const handleUpdateStatus = async (id: number, status: string) => {
    try {
      await api.updatePurchaseOrderStatus(id, status);
      loadOrders();
    } catch (e) {
      console.error(e);
      alert('Failed to update status');
    }
  };

  return (
    <Box>
      <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 700, mb: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
            Purchase Orders <Brain size={28} color="#8b5cf6" />
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Manage manual and AI-generated Smart POs based on demand forecasting.
          </Typography>
        </Box>
        <Button variant="contained" startIcon={<FileText size={18} />}>
          Create Manual PO
        </Button>
      </Box>

      {loading ? (
        <Typography>Loading...</Typography>
      ) : orders.length === 0 ? (
        <Card sx={{ p: 4, textAlign: 'center' }}>
          <Typography color="text.secondary">No Purchase Orders found.</Typography>
        </Card>
      ) : (
        <Grid container spacing={3}>
          {orders.map((po) => (
            <Grid item xs={12} key={po.id}>
              <Card sx={{ 
                borderLeft: po.isAutoGenerated ? '4px solid #8b5cf6' : '4px solid #3b82f6',
                boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' 
              }}>
                <CardContent>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
                    <Box>
                      <Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        PO #{po.id} - {po.supplier.name}
                        {po.isAutoGenerated && (
                          <Chip size="small" icon={<Brain size={14} />} label="AI Drafted" color="secondary" />
                        )}
                        <Chip 
                          size="small" 
                          label={po.status} 
                          color={
                            po.status === 'DRAFT' ? 'warning' :
                            po.status === 'APPROVED' ? 'success' :
                            po.status === 'CANCELLED' ? 'error' : 'default'
                          } 
                        />
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        Created: {new Date(po.createdAt).toLocaleDateString()}
                      </Typography>
                    </Box>
                    <Box sx={{ display: 'flex', gap: 1 }}>
                      {po.status === 'DRAFT' && (
                        <>
                          <Button 
                            variant="outlined" 
                            color="success" 
                            size="small"
                            startIcon={<Check size={16} />}
                            onClick={() => handleUpdateStatus(po.id, 'APPROVED')}
                          >
                            Approve
                          </Button>
                          <Button 
                            variant="outlined" 
                            color="error" 
                            size="small"
                            startIcon={<X size={16} />}
                            onClick={() => handleUpdateStatus(po.id, 'CANCELLED')}
                          >
                            Reject
                          </Button>
                        </>
                      )}
                      <IconButton size="small" color="primary">
                        <Eye size={20} />
                      </IconButton>
                    </Box>
                  </Box>

                  <Table size="small">
                    <TableHead>
                      <TableRow>
                        <TableCell>Product</TableCell>
                        <TableCell>Reason</TableCell>
                        <TableCell align="right">Qty</TableCell>
                        <TableCell align="right">Est. Total</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {po.items.map((item: any) => (
                        <TableRow key={item.id}>
                          <TableCell sx={{ fontWeight: 500 }}>{item.product.name}</TableCell>
                          <TableCell sx={{ color: 'text.secondary', fontSize: '0.85rem' }}>
                            {item.reason || '-'}
                          </TableCell>
                          <TableCell align="right">{item.requestedQuantity}</TableCell>
                          <TableCell align="right">₹{(item.requestedQuantity * item.estimatedPrice).toFixed(2)}</TableCell>
                        </TableRow>
                      ))}
                      <TableRow>
                        <TableCell colSpan={3} align="right" sx={{ fontWeight: 'bold' }}>Total:</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold' }}>₹{po.estimatedTotal.toFixed(2)}</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}
    </Box>
  );
}
