import React, { useEffect, useState } from 'react';
import {
  Box,
  Typography,
  Button,
  Card,
  CardContent,
  Grid,
  Chip,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  Stack,
  Alert,
} from '@mui/material';
import { Brain, FileText, Check, X, Eye, Plus, Trash } from 'lucide-react';
import { api } from '../api/client';
import type { Product, Supplier } from '../types';

export default function PurchaseOrders() {
  const [orders, setOrders] = useState<any[]>([]);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);

  // Dialog State
  const [openDialog, setOpenDialog] = useState(false);
  const [supplierId, setSupplierId] = useState<number | ''>('');
  const [notes, setNotes] = useState('');
  const [items, setItems] = useState<any[]>([]);

  // Item form state
  const [itemProductId, setItemProductId] = useState<number | ''>('');
  const [itemQty, setItemQty] = useState<string>('');
  const [itemPrice, setItemPrice] = useState<string>('');

  const [error, setError] = useState('');

  const loadOrders = () => {
    setLoading(true);
    api.getPurchaseOrders()
      .then(setOrders)
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  const loadDropdowns = async () => {
    try {
      const s = await api.get<Supplier[]>('/suppliers');
      const p = await api.get<Product[]>('/products');
      setSuppliers(s);
      setProducts(p);
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    loadOrders();
    loadDropdowns();
  }, []);

  const handleUpdateStatus = async (id: number, status: string) => {
    try {
      await api.updatePurchaseOrderStatus(id, status);
      loadOrders();
    } catch (e) {
      console.error(e);
      alert('Failed to update status');
    }
  };

  const handleAddItem = () => {
    if (!itemProductId || !itemQty || !itemPrice) return;
    const prod = products.find(p => p.id === itemProductId);
    if (!prod) return;

    setItems([...items, {
      productId: itemProductId,
      productName: prod.name,
      quantity: parseInt(itemQty),
      estimatedPrice: parseFloat(itemPrice),
      reason: 'Manual request',
    }]);

    setItemProductId('');
    setItemQty('');
    setItemPrice('');
  };

  const handleRemoveItem = (index: number) => {
    setItems(items.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!supplierId || items.length === 0) return;

    const payload = {
      supplierId,
      notes,
      isAutoGenerated: false,
      items: items.map(item => ({
        productId: item.productId,
        quantity: item.quantity,
        estimatedPrice: item.estimatedPrice,
        reason: item.reason,
      })),
    };

    try {
      setError('');
      await api.post('/purchase-orders', payload);
      setOpenDialog(false);
      setSupplierId('');
      setNotes('');
      setItems([]);
      loadOrders();
    } catch (e: any) {
      console.error(e);
      setError(e.message || 'Failed to create Purchase Order');
    }
  };

  return (
    <Box>
      <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 700, mb: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
            Purchase Orders <Brain size={28} color="#8b5cf6" />
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Manage manual and AI-generated Smart POs based on demand forecasting.
          </Typography>
        </Box>
        <Button variant="contained" startIcon={<FileText size={18} />} onClick={() => setOpenDialog(true)}>
          Create Manual PO
        </Button>
      </Box>

      {loading ? (
        <Typography>Loading...</Typography>
      ) : orders.length === 0 ? (
        <Card sx={{ p: 4, textAlign: 'center' }}>
          <Typography color="text.secondary">No Purchase Orders found.</Typography>
        </Card>
      ) : (
        <Grid container spacing={3}>
          {orders.map((po) => (
            <Grid item xs={12} key={po.id}>
              <Card sx={{ 
                borderLeft: po.isAutoGenerated ? '4px solid #8b5cf6' : '4px solid #3b82f6',
                boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' 
              }}>
                <CardContent>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
                    <Box>
                      <Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        PO #{po.id} - {po.supplier?.name || 'Unknown'}
                        {po.isAutoGenerated && (
                          <Chip size="small" icon={<Brain size={14} />} label="AI Drafted" color="secondary" />
                        )}
                        <Chip 
                          size="small" 
                          label={po.status} 
                          color={
                            po.status === 'DRAFT' ? 'warning' :
                            po.status === 'APPROVED' ? 'success' :
                            po.status === 'CANCELLED' ? 'error' : 'default'
                          } 
                        />
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        Created: {po.createdAt ? new Date(po.createdAt).toLocaleDateString() : 'N/A'}
                      </Typography>
                    </Box>
                    <Box sx={{ display: 'flex', gap: 1 }}>
                      {po.status === 'DRAFT' && (
                        <>
                          <Button 
                            variant="outlined" 
                            color="success" 
                            size="small"
                            startIcon={<Check size={16} />}
                            onClick={() => handleUpdateStatus(po.id, 'APPROVED')}
                          >
                            Approve
                          </Button>
                          <Button 
                            variant="outlined" 
                            color="error" 
                            size="small"
                            startIcon={<X size={16} />}
                            onClick={() => handleUpdateStatus(po.id, 'CANCELLED')}
                          >
                            Reject
                          </Button>
                        </>
                      )}
                    </Box>
                  </Box>

                  <Table size="small">
                    <TableHead>
                      <TableRow>
                        <TableCell>Product</TableCell>
                        <TableCell>Reason</TableCell>
                        <TableCell align="right">Qty</TableCell>
                        <TableCell align="right">Est. Total</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {po.items.map((item: any) => (
                        <TableRow key={item.id}>
                          <TableCell sx={{ fontWeight: 500 }}>{item.product?.name || 'Unknown'}</TableCell>
                          <TableCell sx={{ color: 'text.secondary', fontSize: '0.85rem' }}>
                            {item.reason || '-'}
                          </TableCell>
                          <TableCell align="right">{item.requestedQuantity}</TableCell>
                          <TableCell align="right">₹{(item.requestedQuantity * item.estimatedPrice).toFixed(2)}</TableCell>
                        </TableRow>
                      ))}
                      <TableRow>
                        <TableCell colSpan={3} align="right" sx={{ fontWeight: 'bold' }}>Total:</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold' }}>₹{(po.estimatedTotal || 0).toFixed(2)}</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}

      {/* Create PO Dialog */}
      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>Create Manual Purchase Order</DialogTitle>
        <form onSubmit={handleSubmit}>
          <DialogContent>
            {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
            
            <Grid container spacing={2}>
              <Grid item xs={12} sm={6}>
                <TextField
                  select
                  fullWidth
                  label="Select Supplier"
                  required
                  value={supplierId}
                  onChange={(e) => setSupplierId(Number(e.target.value))}
                >
                  {suppliers.map(s => (
                    <MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>
                  ))}
                </TextField>
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Notes"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                />
              </Grid>
            </Grid>

            <Typography variant="subtitle1" sx={{ mt: 3, mb: 1, fontWeight: 'bold' }}>Items</Typography>
            
            {/* Add Item Form Row */}
            <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mb: 2 }}>
              <TextField
                select
                fullWidth
                label="Product"
                value={itemProductId}
                onChange={(e) => {
                  const pid = Number(e.target.value);
                  setItemProductId(pid);
                  const p = products.find(prod => prod.id === pid);
                  if (p) setItemPrice(p.costPrice.toString());
                }}
              >
                {products.map(p => (
                  <MenuItem key={p.id} value={p.id}>{p.name} ({p.partNumber})</MenuItem>
                ))}
              </TextField>
              <TextField
                label="Quantity"
                type="number"
                value={itemQty}
                onChange={(e) => setItemQty(e.target.value)}
                inputProps={{ min: 1 }}
              />
              <TextField
                label="Est. Unit Price (₹)"
                type="number"
                value={itemPrice}
                onChange={(e) => setItemPrice(e.target.value)}
              />
              <Button 
                variant="outlined" 
                startIcon={<Plus size={16} />} 
                onClick={handleAddItem}
                disabled={!itemProductId || !itemQty || !itemPrice}
                sx={{ px: 3 }}
              >
                Add
              </Button>
            </Stack>

            {/* Added Items Table */}
            <Table size="small" sx={{ mt: 2 }}>
              <TableHead>
                <TableRow>
                  <TableCell>Product Name</TableCell>
                  <TableCell align="right">Qty</TableCell>
                  <TableCell align="right">Unit Price</TableCell>
                  <TableCell align="right">Total</TableCell>
                  <TableCell align="center">Action</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {items.map((item, index) => (
                  <TableRow key={index}>
                    <TableCell>{item.productName}</TableCell>
                    <TableCell align="right">{item.quantity}</TableCell>
                    <TableCell align="right">₹{item.estimatedPrice.toFixed(2)}</TableCell>
                    <TableCell align="right">₹{(item.quantity * item.estimatedPrice).toFixed(2)}</TableCell>
                    <TableCell align="center">
                      <IconButton color="error" size="small" onClick={() => handleRemoveItem(index)}>
                        <Trash size={16} />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
                {items.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={5} align="center" sx={{ color: 'text.secondary', py: 2 }}>
                      No items added yet.
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setOpenDialog(false)}>Cancel</Button>
            <Button type="submit" variant="contained" disabled={items.length === 0 || !supplierId}>
              Create Purchase Order
            </Button>
          </DialogActions>
        </form>
      </Dialog>
    </Box>
  );
}
